//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InterConnect.LeshLaonApi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LeshLoanAPISoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Status))]
    public partial class LeshLoanAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteNonQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveClientDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAdditionalClientDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSystemUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveSystemSettingOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveLoanDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LeshLoanAPI() {
            this.Url = global::InterConnect.Properties.Settings.Default.InterConnect_UBAApi_UBAKYCAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteDataSetCompletedEventHandler ExecuteDataSetCompleted;
        
        /// <remarks/>
        public event ExecuteNonQueryCompletedEventHandler ExecuteNonQueryCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogOutCompletedEventHandler LogOutCompleted;
        
        /// <remarks/>
        public event SaveClientDetailsCompletedEventHandler SaveClientDetailsCompleted;
        
        /// <remarks/>
        public event SaveAdditionalClientDetailsCompletedEventHandler SaveAdditionalClientDetailsCompleted;
        
        /// <remarks/>
        public event SaveSystemUserCompletedEventHandler SaveSystemUserCompleted;
        
        /// <remarks/>
        public event SaveSystemSettingCompletedEventHandler SaveSystemSettingCompleted;
        
        /// <remarks/>
        public event SaveLoanDetailsCompletedEventHandler SaveLoanDetailsCompleted;
        
        /// <remarks/>
        public event GetClientDetailsCompletedEventHandler GetClientDetailsCompleted;
        
        /// <remarks/>
        public event ResetPasswordCompletedEventHandler ResetPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ExecuteDataSet(string storedProcName, string[] parameters) {
            object[] results = this.Invoke("ExecuteDataSet", new object[] {
                        storedProcName,
                        parameters});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataSetAsync(string storedProcName, string[] parameters) {
            this.ExecuteDataSetAsync(storedProcName, parameters, null);
        }
        
        /// <remarks/>
        public void ExecuteDataSetAsync(string storedProcName, string[] parameters, object userState) {
            if ((this.ExecuteDataSetOperationCompleted == null)) {
                this.ExecuteDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataSetOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataSet", new object[] {
                        storedProcName,
                        parameters}, this.ExecuteDataSetOperationCompleted, userState);
        }
        
        private void OnExecuteDataSetOperationCompleted(object arg) {
            if ((this.ExecuteDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataSetCompleted(this, new ExecuteDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteNonQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ExecuteNonQuery(string storedProcName, string[] parameters) {
            object[] results = this.Invoke("ExecuteNonQuery", new object[] {
                        storedProcName,
                        parameters});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteNonQueryAsync(string storedProcName, string[] parameters) {
            this.ExecuteNonQueryAsync(storedProcName, parameters, null);
        }
        
        /// <remarks/>
        public void ExecuteNonQueryAsync(string storedProcName, string[] parameters, object userState) {
            if ((this.ExecuteNonQueryOperationCompleted == null)) {
                this.ExecuteNonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteNonQueryOperationCompleted);
            }
            this.InvokeAsync("ExecuteNonQuery", new object[] {
                        storedProcName,
                        parameters}, this.ExecuteNonQueryOperationCompleted, userState);
        }
        
        private void OnExecuteNonQueryOperationCompleted(object arg) {
            if ((this.ExecuteNonQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteNonQueryCompleted(this, new ExecuteNonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemUser Login(string UserId, string Password, string Identifier) {
            object[] results = this.Invoke("Login", new object[] {
                        UserId,
                        Password,
                        Identifier});
            return ((SystemUser)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string UserId, string Password, string Identifier) {
            this.LoginAsync(UserId, Password, Identifier, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string UserId, string Password, string Identifier, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        UserId,
                        Password,
                        Identifier}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result LogOut(string UserId) {
            object[] results = this.Invoke("LogOut", new object[] {
                        UserId});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void LogOutAsync(string UserId) {
            this.LogOutAsync(UserId, null);
        }
        
        /// <remarks/>
        public void LogOutAsync(string UserId, object userState) {
            if ((this.LogOutOperationCompleted == null)) {
                this.LogOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOutOperationCompleted);
            }
            this.InvokeAsync("LogOut", new object[] {
                        UserId}, this.LogOutOperationCompleted, userState);
        }
        
        private void OnLogOutOperationCompleted(object arg) {
            if ((this.LogOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOutCompleted(this, new LogOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveClientDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveClientDetails(ClientDetails req) {
            object[] results = this.Invoke("SaveClientDetails", new object[] {
                        req});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveClientDetailsAsync(ClientDetails req) {
            this.SaveClientDetailsAsync(req, null);
        }
        
        /// <remarks/>
        public void SaveClientDetailsAsync(ClientDetails req, object userState) {
            if ((this.SaveClientDetailsOperationCompleted == null)) {
                this.SaveClientDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveClientDetailsOperationCompleted);
            }
            this.InvokeAsync("SaveClientDetails", new object[] {
                        req}, this.SaveClientDetailsOperationCompleted, userState);
        }
        
        private void OnSaveClientDetailsOperationCompleted(object arg) {
            if ((this.SaveClientDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveClientDetailsCompleted(this, new SaveClientDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveAdditionalClientDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveAdditionalClientDetails(ClientDetails req) {
            object[] results = this.Invoke("SaveAdditionalClientDetails", new object[] {
                        req});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAdditionalClientDetailsAsync(ClientDetails req) {
            this.SaveAdditionalClientDetailsAsync(req, null);
        }
        
        /// <remarks/>
        public void SaveAdditionalClientDetailsAsync(ClientDetails req, object userState) {
            if ((this.SaveAdditionalClientDetailsOperationCompleted == null)) {
                this.SaveAdditionalClientDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAdditionalClientDetailsOperationCompleted);
            }
            this.InvokeAsync("SaveAdditionalClientDetails", new object[] {
                        req}, this.SaveAdditionalClientDetailsOperationCompleted, userState);
        }
        
        private void OnSaveAdditionalClientDetailsOperationCompleted(object arg) {
            if ((this.SaveAdditionalClientDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAdditionalClientDetailsCompleted(this, new SaveAdditionalClientDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveSystemUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSystemUser(SystemUser user) {
            object[] results = this.Invoke("SaveSystemUser", new object[] {
                        user});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSystemUserAsync(SystemUser user) {
            this.SaveSystemUserAsync(user, null);
        }
        
        /// <remarks/>
        public void SaveSystemUserAsync(SystemUser user, object userState) {
            if ((this.SaveSystemUserOperationCompleted == null)) {
                this.SaveSystemUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSystemUserOperationCompleted);
            }
            this.InvokeAsync("SaveSystemUser", new object[] {
                        user}, this.SaveSystemUserOperationCompleted, userState);
        }
        
        private void OnSaveSystemUserOperationCompleted(object arg) {
            if ((this.SaveSystemUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSystemUserCompleted(this, new SaveSystemUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveSystemSetting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveSystemSetting(SystemSetting req) {
            object[] results = this.Invoke("SaveSystemSetting", new object[] {
                        req});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveSystemSettingAsync(SystemSetting req) {
            this.SaveSystemSettingAsync(req, null);
        }
        
        /// <remarks/>
        public void SaveSystemSettingAsync(SystemSetting req, object userState) {
            if ((this.SaveSystemSettingOperationCompleted == null)) {
                this.SaveSystemSettingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveSystemSettingOperationCompleted);
            }
            this.InvokeAsync("SaveSystemSetting", new object[] {
                        req}, this.SaveSystemSettingOperationCompleted, userState);
        }
        
        private void OnSaveSystemSettingOperationCompleted(object arg) {
            if ((this.SaveSystemSettingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveSystemSettingCompleted(this, new SaveSystemSettingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveLoanDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SaveLoanDetails(LoanDetails req) {
            object[] results = this.Invoke("SaveLoanDetails", new object[] {
                        req});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SaveLoanDetailsAsync(LoanDetails req) {
            this.SaveLoanDetailsAsync(req, null);
        }
        
        /// <remarks/>
        public void SaveLoanDetailsAsync(LoanDetails req, object userState) {
            if ((this.SaveLoanDetailsOperationCompleted == null)) {
                this.SaveLoanDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveLoanDetailsOperationCompleted);
            }
            this.InvokeAsync("SaveLoanDetails", new object[] {
                        req}, this.SaveLoanDetailsOperationCompleted, userState);
        }
        
        private void OnSaveLoanDetailsOperationCompleted(object arg) {
            if ((this.SaveLoanDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveLoanDetailsCompleted(this, new SaveLoanDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientDetails[] GetClientDetails(string BankCode, string UserId, string ClientID) {
            object[] results = this.Invoke("GetClientDetails", new object[] {
                        BankCode,
                        UserId,
                        ClientID});
            return ((ClientDetails[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync(string BankCode, string UserId, string ClientID) {
            this.GetClientDetailsAsync(BankCode, UserId, ClientID, null);
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync(string BankCode, string UserId, string ClientID, object userState) {
            if ((this.GetClientDetailsOperationCompleted == null)) {
                this.GetClientDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientDetailsOperationCompleted);
            }
            this.InvokeAsync("GetClientDetails", new object[] {
                        BankCode,
                        UserId,
                        ClientID}, this.GetClientDetailsOperationCompleted, userState);
        }
        
        private void OnGetClientDetailsOperationCompleted(object arg) {
            if ((this.GetClientDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientDetailsCompleted(this, new GetClientDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResetPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result ResetPassword(SystemUser Reset) {
            object[] results = this.Invoke("ResetPassword", new object[] {
                        Reset});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ResetPasswordAsync(SystemUser Reset) {
            this.ResetPasswordAsync(Reset, null);
        }
        
        /// <remarks/>
        public void ResetPasswordAsync(SystemUser Reset, object userState) {
            if ((this.ResetPasswordOperationCompleted == null)) {
                this.ResetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetPasswordOperationCompleted);
            }
            this.InvokeAsync("ResetPassword", new object[] {
                        Reset}, this.ResetPasswordOperationCompleted, userState);
        }
        
        private void OnResetPasswordOperationCompleted(object arg) {
            if ((this.ResetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetPasswordCompleted(this, new ResetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemUser : Entity {
        
        private string userIdField;
        
        private string passwordField;
        
        private string nameField;
        
        private string roleCodeField;
        
        private string isActiveField;
        
        private string emailField;
        
        private bool resetPasswordField;
        
        /// <remarks/>
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string RoleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool ResetPassword {
            get {
                return this.resetPasswordField;
            }
            set {
                this.resetPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoanDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSetting))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entity : Status {
        
        private string recordIdField;
        
        private string companyCodeField;
        
        private string createdByField;
        
        private string modifiedByField;
        
        private string createdOnField;
        
        private string modifiedOnField;
        
        /// <remarks/>
        public string RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoanDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemSetting))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDetails))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Status {
        
        private string statusCodeField;
        
        private string statusDescField;
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result : Status {
        
        private string loanIDField;
        
        private string requestIDField;
        
        private string thirdPartYIDField;
        
        /// <remarks/>
        public string LoanID {
            get {
                return this.loanIDField;
            }
            set {
                this.loanIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public string ThirdPartYID {
            get {
                return this.thirdPartYIDField;
            }
            set {
                this.thirdPartYIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoanDetails : Entity {
        
        private string clientIDField;
        
        private string loanNoField;
        
        private string loanAmountField;
        
        private string loanDescField;
        
        private string loanDateField;
        
        private string interestRateField;
        
        private string approvedAmountField;
        
        private string lastLoanAmountField;
        
        private string currentDebtField;
        
        private string organizationField;
        
        private string monthsToPayInField;
        
        private string easyPaidAmountPerMonthField;
        
        private string approvedField;
        
        private string agreeToLoanAggreementField;
        
        private string nameField;
        
        private string typeField;
        
        private string modelField;
        
        private string makeField;
        
        private string serialNumberField;
        
        private string estimatedPriceField;
        
        private string imageProofField;
        
        private string observationsField;
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string LoanNo {
            get {
                return this.loanNoField;
            }
            set {
                this.loanNoField = value;
            }
        }
        
        /// <remarks/>
        public string LoanAmount {
            get {
                return this.loanAmountField;
            }
            set {
                this.loanAmountField = value;
            }
        }
        
        /// <remarks/>
        public string LoanDesc {
            get {
                return this.loanDescField;
            }
            set {
                this.loanDescField = value;
            }
        }
        
        /// <remarks/>
        public string LoanDate {
            get {
                return this.loanDateField;
            }
            set {
                this.loanDateField = value;
            }
        }
        
        /// <remarks/>
        public string InterestRate {
            get {
                return this.interestRateField;
            }
            set {
                this.interestRateField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovedAmount {
            get {
                return this.approvedAmountField;
            }
            set {
                this.approvedAmountField = value;
            }
        }
        
        /// <remarks/>
        public string LastLoanAmount {
            get {
                return this.lastLoanAmountField;
            }
            set {
                this.lastLoanAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentDebt {
            get {
                return this.currentDebtField;
            }
            set {
                this.currentDebtField = value;
            }
        }
        
        /// <remarks/>
        public string Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string MonthsToPayIn {
            get {
                return this.monthsToPayInField;
            }
            set {
                this.monthsToPayInField = value;
            }
        }
        
        /// <remarks/>
        public string EasyPaidAmountPerMonth {
            get {
                return this.easyPaidAmountPerMonthField;
            }
            set {
                this.easyPaidAmountPerMonthField = value;
            }
        }
        
        /// <remarks/>
        public string Approved {
            get {
                return this.approvedField;
            }
            set {
                this.approvedField = value;
            }
        }
        
        /// <remarks/>
        public string AgreeToLoanAggreement {
            get {
                return this.agreeToLoanAggreementField;
            }
            set {
                this.agreeToLoanAggreementField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedPrice {
            get {
                return this.estimatedPriceField;
            }
            set {
                this.estimatedPriceField = value;
            }
        }
        
        /// <remarks/>
        public string ImageProof {
            get {
                return this.imageProofField;
            }
            set {
                this.imageProofField = value;
            }
        }
        
        /// <remarks/>
        public string Observations {
            get {
                return this.observationsField;
            }
            set {
                this.observationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemSetting : Entity {
        
        private string settingCodeField;
        
        private string settingValueField;
        
        /// <remarks/>
        public string SettingCode {
            get {
                return this.settingCodeField;
            }
            set {
                this.settingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SettingValue {
            get {
                return this.settingValueField;
            }
            set {
                this.settingValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientDetails : Entity {
        
        private string clientNoField;
        
        private string clientNameField;
        
        private string clientAddressField;
        
        private string clientPhoneNumberField;
        
        private string refereeField;
        
        private string refrereePhoneNoField;
        
        private string genderField;
        
        private string iDTypeField;
        
        private string iDNumberField;
        
        private string iDPhotoField;
        
        private string clientPhotoField;
        
        private string clientEmailField;
        
        private string clientPasswordField;
        
        private string dOBField;
        
        private string businessLocField;
        
        private string occupationField;
        
        private string noOfBeneficiariesField;
        
        private string educLevelField;
        
        private string monthlyIncomeField;
        
        /// <remarks/>
        public string ClientNo {
            get {
                return this.clientNoField;
            }
            set {
                this.clientNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClientAddress {
            get {
                return this.clientAddressField;
            }
            set {
                this.clientAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPhoneNumber {
            get {
                return this.clientPhoneNumberField;
            }
            set {
                this.clientPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Referee {
            get {
                return this.refereeField;
            }
            set {
                this.refereeField = value;
            }
        }
        
        /// <remarks/>
        public string RefrereePhoneNo {
            get {
                return this.refrereePhoneNoField;
            }
            set {
                this.refrereePhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string IDType {
            get {
                return this.iDTypeField;
            }
            set {
                this.iDTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IDNumber {
            get {
                return this.iDNumberField;
            }
            set {
                this.iDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IDPhoto {
            get {
                return this.iDPhotoField;
            }
            set {
                this.iDPhotoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPhoto {
            get {
                return this.clientPhotoField;
            }
            set {
                this.clientPhotoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientEmail {
            get {
                return this.clientEmailField;
            }
            set {
                this.clientEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPassword {
            get {
                return this.clientPasswordField;
            }
            set {
                this.clientPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string BusinessLoc {
            get {
                return this.businessLocField;
            }
            set {
                this.businessLocField = value;
            }
        }
        
        /// <remarks/>
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }
        
        /// <remarks/>
        public string NoOfBeneficiaries {
            get {
                return this.noOfBeneficiariesField;
            }
            set {
                this.noOfBeneficiariesField = value;
            }
        }
        
        /// <remarks/>
        public string EducLevel {
            get {
                return this.educLevelField;
            }
            set {
                this.educLevelField = value;
            }
        }
        
        /// <remarks/>
        public string MonthlyIncome {
            get {
                return this.monthlyIncomeField;
            }
            set {
                this.monthlyIncomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteDataSetCompletedEventHandler(object sender, ExecuteDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteNonQueryCompletedEventHandler(object sender, ExecuteNonQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LogOutCompletedEventHandler(object sender, LogOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveClientDetailsCompletedEventHandler(object sender, SaveClientDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveClientDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveClientDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveAdditionalClientDetailsCompletedEventHandler(object sender, SaveAdditionalClientDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAdditionalClientDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAdditionalClientDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveSystemUserCompletedEventHandler(object sender, SaveSystemUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSystemUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSystemUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveSystemSettingCompletedEventHandler(object sender, SaveSystemSettingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveSystemSettingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveSystemSettingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaveLoanDetailsCompletedEventHandler(object sender, SaveLoanDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveLoanDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveLoanDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetClientDetailsCompletedEventHandler(object sender, GetClientDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientDetails[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientDetails[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ResetPasswordCompletedEventHandler(object sender, ResetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591